name = "ImGuiOpenGLBackend"
uuid = "9d0819b4-44e7-43a2-ad03-8fb999128168"
authors = ["Yupei Qi <qiyupei@gmail.com>"]
version = "0.1.1"

[deps]
LibCImGui = "9be01004-c4f5-478b-abeb-cb32b114cf5e"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[compat]
julia = "1.6"
LibCImGui = "1.82.2"
ModernGL = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
